### ISSUE TITLE
Can a GPU reproduce the result?

### ISSUE THREAD

**Issue by 2081147463** [yoonkicho/PPLR#13]
I have a GPU（NVIDIA 2080ti 11G）, I used the default parameters and code, the result of running is very bad, please ask how to adjust if it is a parameter problem, I hope to be able to answer

Mean AP: 71.6%
CMC Scores:
  top-1          86.7%
  top-5          92.9%
  top-10         95.4%

**Comment by yoonkicho** [comment]
Hi, thank you for your interest.
Unsupervised re-ID training is very sensitive to the number of GPUs and batch sizes, and I think single GPU training is hard to reproduce the results in the paper.
Please refer #5

**Comment by 2081147463** [comment]
Thank you
