### ISSUE TITLE
Regarding the "Unsupervised" Claim

### ISSUE THREAD

**Issue by KleinYuan** [yoonkicho/PPLR#14]
First of all, I would like to appreciate the great work.
Second, I noticed that in your work, when you do clustering, you still use the pids: https://github.com/yoonkicho/PPLR/blob/main/examples/train_pplr.py#L215-L219.

Namely, say, for the Market-1501 datasets, we have the below examples:
1. 0002_c1s1_000451_03.jpg  
2. 0002_c1s1_000551_01.jpg  
3. 0886_c6s2_103418_03.jpg
4. 0430_c5s1_109723_02.jpg 

You are still using the information of 1&2 are the observations of the same person right ?

I am trying to see that if I only have a folder of detection results (say 10000 crops but no identity labels), does PPLR still works ?

**Comment by yoonkicho** [comment]
Hi, thank your for your interest to our work.

1. As written in [the #L191~L199 of the code](https://github.com/yoonkicho/PPLR/blob/main/examples/train_pplr.py#L191-L199), 'pids' gets the label from 'pseudo_labels' which is from DBSCAN clustering (see #L181).

2. Yes. As PPLR works without identity labels, you can use it with proper dataset and data loaders.
