### ISSUE TITLE
A few questions about the code implementation

### ISSUE THREAD

**Issue by InstantWindy** [yoonkicho/PPLR#15]
1. The paper states that the part features are  obtained by dividing the feature map into Np uniformly partitioned regions. 
     But in the code, this division  is achieved by the nn.AdaptiveAvgPool2d((self.num_parts, 1)) operation, The two clearly do not match up
2. This paper does not mention anything about aals_ epoch parameter settings. Why is the aals_ epoch value set to 5

**Comment by yoonkicho** [comment]
Hi, thank you for your interest.

1. nn.AdaptiveAvgPool2d((self.num_parts, 1)) operation divide the input feature map into N_p uniformly partitioned regions (w/ shape (B*C*H/self.num_parts*W) and then apply average pooling. S, it works as described in the paper.

2. More implementation details are included in the appendix. In early training epochs, overall cross-agreement score are significantly low, which results in a very strong label smoothing effect and is detrimental to training. For stable training, we apply the agreement-aware label smoothing after the first five epochs.

I hope this helps you.
