### ISSUE TITLE
Hello Professor. When using the DukeMTMC dataset, labeled training can be run through, but the data for unlabeled training is very low. What is the reason?

### ISSUE THREAD

**Issue by LYL-hub-source** [yoonkicho/PPLR#17]
Can I use the DukeMTMC dataset for training?

**Comment by yoonkicho** [comment]
Sure. You can use our code to train a model with DukeMTMC dataset.
We updated the code related to loading DukeMTMC dataset.
I hope this helps you.

BTW, DukeMTMC-reID has been withdrawn and is not available now.
