### ISSUE TITLE
the visualization method

### ISSUE THREAD

**Issue by luluaa** [yoonkicho/PPLR#3]
Thank you for your wonderful work！Could you give me the reference code for the t-SNE visualization in Figure 2? I want to find out what's wrong with the clustering results in my work through visualization. Thanks！！！!

**Comment by yoonkicho** [comment]
Hi,
Thank you for your interest. We did t-sne visualizations based on the code example in this [link](https://learnopencv.com/t-sne-for-feature-visualization/).
