### ISSUE TITLE
Questions about self-trained source code

### ISSUE THREAD

**Issue by Estella218** [yoonkicho/PPLR#5]
Hello, author. In the process of self-training published source code, I used the configuration of one GPU and got a result about 10% different from the paper. Do you need 4 Gpus to achieve the latest effect? Is there another way to get out?

**Comment by krmui** [comment]
If you run with one GPU, the corresponding batchsize should be adjusted to one quarter. If you have two, it should be adjusted to one half

**Comment by yoonkicho** [comment]
Hi, 
Unfortunately, unsupervised re-ID training is sensitive to the number of GPUs and batch size.
As mentioned above, adjusting the batch size can show better performance, but I'm not sure if it shows similar performance to when using 4 GPUs.
BTW, we upload the pre-trained weights by our method, and you can download this via [link](https://drive.google.com/drive/folders/1m5wDOJG7qk62PjkoOpTspNmk0nhLc4Vi).
I hope this helps you.
