### ISSUE TITLE
cross agreement score problem

### ISSUE THREAD

**Issue by krmui** [yoonkicho/PPLR#7]
I want to ask why the cross consent score in each epoch is changing. According to my own understanding, the characteristics of the image have not changed, and the similarity calculated by the jackard distance of the complete image and part of the image has not changed. Shouldn't the cross consent score in each epoch be the same？

**Comment by yoonkicho** [comment]
Hi,
Could you elaborate more? 
We compute cross agreement scores once before a training epoch, and a model will be trained with the same cross agreement score during that epoch.
After training stage(epoch), we extract updated features with a trained model for clustering and cross agreement scores, and then we update cross agreement scores based on updated features.
