### ISSUE TITLE
cluster

### ISSUE THREAD

**Issue by krmui** [yoonkicho/PPLR#8]
I would like to ask if you only performed DBSCAN clustering once at epoch 0, but did not cluster at epoch 0?

**Comment by yoonkicho** [comment]
We perform DBSCAN clusterings on each epoch to compute pseudo-labels and cross agreement scores.

**Comment by YpSokm** [comment]
Sorry, the following is the result of my reproduction of your code on NVIDIA GeForce 3090. I ran 50 epochs.
Mean AP: 58.5%
CMC Scores:
  top-1          78.4%
  top-5          85.6%
  top-10         87.9%
Is my configuration errors?
